jobs:
  include:
    - stage: unit test
      language: python
      catch: pip
      python:
        - "3.6"
      # command to install dependencies
      install:
        - pip install -r requirements.txt
        - pip install .
      # command to run tests
      script: pytest

    - stage: release to pypi
      if: type = push
      language: python
      catch: pip
      python:
      - "3.6"
      script:
      - echo "Skipping tests"
      deploy:
        provider: pypi
        user: YurRee
        password:
          secure: "tCZtCFBUERTi0cRlkjArOyck3UCmyis9SlwFy8GuPkm7N+Srkc7dapNV2lezNn82yzyKDE9VoxfMEg3V296TcOD10iUGWw8HPyQ7Zfx9Ir6nyPYSsoi1rbxVGuzNuJRmo/x2m1o86bjYIdbV1lzxPWsrkrxTzqVRhG3bRB9G47QGjEImKcDERX0xRU4glex/oUnoT/qq0551nzv92JwJYVFKsQzpIOKYAMNcv3/QM3Hgih0oxPva9jkQN5M4nPEm2izFeLF1REipo0rA2x88WL9pjmLwxLbRiArYQVkyrylpVBaATZ47E3ig/AKdhNMlOG47BHIMa293sHBWka1kS5NuU7Fhpkary5dEQo1B0B8aw/VktgeVdGtUAURAa0xq5IagJjYchkjSJrQBdl0y2bgH4qEzLKoMMduM1XSVeVfvEvaNBmYyKgCkxk80KeRlo+/b9O5AwkAzCvDXTiEhsWLMdIlNeBLZHpEjvcPcMHXmxpiTXU+YzT7JABuiZF/vuKXIGFCIUr7+Dptu/jmRFZTqb5wzxOqYCTXXpGP5svHWSFoyALSDIeC+/7+7SKTKKmpyG/785aqaB0T40i7WQ85yWcWoLQTxCClrxYmy0dqQFYwtl9VmVMDsv/szmlndnguV4wWaS+H4e1ZL+W5s1V5THyzYMkru8VTeEvfkSPk="
        on:
          tags: true
