jobs:
  include:
    - stage: unit test
      language: python
      catch: pip
      python:
        - "3.6"
      # command to install dependencies
      install:
        - pip install -r requirements.txt
        - pip install .
      # command to run tests
      script: pytest

    - stage: release to pypi
      if: type = push AND tag IS present
      language: python
      catch: 
        - pip
        - npm
      python:
        - "3.6"
      node_js:
        - "10"
      install:
        - cd frontend
        - npm install
        - npm run build
        - cd ..
      script:
        - echo "No script for pypi release"
      deploy:
        provider: pypi
        skip_existing: true
        skip-cleanup: true
        user: yumiguan
        password:
          secure: "OOHysTCqFWBkK9i32G60FqhvqMmKgyUzSM9FIdX7j5NESnC4t2BxDZg13e2MOpV0iAUdq0zRSHuxBY/KbiLnpVbI2RWPEOD6v5efQNkNmLKoElzi4PhTnG2CxJGqwg9I0DH2qWgrSPDae5ikQpRvhqsD+G9yYDW1ge4mgGk0ui+xNAETjDswkmFOShH18mvwqdf543aoyVtmjJVMtWPoMTgqBuQL/JhCeg/xojfza0vz8sF4a1uB34kNS9femjTMXgeuPeFqX9LzHcsM3kl5t+SRi6jH86pCnqt1yyXExX0K/izpnQh9qa1Oze+NlHrVqgODYjjuSvfbtVR9hJuw+C5d0WHXfBk9BALs8hG8C51+mqQ3EBfjAUfCjBGr9yXkraaaGo/BiFrmZpKVBzG3lAkHb8/uRfg9tR87F7dxQ/uqr3qsRCtfzvk2Msc5fNczJJV0+JswdgsgJeczXU7+p/6rGIQ3TVcLKjammfLL7pPqJeP0TPNZ7SL+VDDmvusNJeYGvd4mfx1m1MpW1onhon3HsDwhd14dApIuS+vZAw0Uf9CtDZ0QMHE76+YAlnZpwA93c65+Td1gMQlL69w0wYQl76X36sLxlAmuOAzxPawscN2ampYHx6oqSkHtqkIiDz6Dr+/hUJhGRmcGbxFMGQVroP4KmJUfATITqQ3KYkc="
        on:
          tags: true
